# Generated by Django 6.1.1 on 2026-09-17 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cotisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('libelle', models.CharField(max_length=255)),
                ('date_operation', models.DateTimeField(auto_now_add=True)),
                ('cotisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='cotisations.cotisation')),
            ],
            options={
                'verbose_name': 'Opération financière',
                'verbose_name_plural': 'Opérations financières',
                'db_table': 'historique_operation',
                'ordering': ['-date_operation'],
            },
        ),
    ]
