# Generated by Django 6.1.1 on 2026-09-17 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_utilisateur_is_active_utilisateur_is_staff'),
        ('historiques', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiqueoperation',
            name='gie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historique_operations', to='authentication.gie'),
        ),
    ]
