# Generated by Django 6.1.1 on 2026-09-26 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiques', '0002_historiqueoperation_gie'),
        ('prets', '0005_pret_token_decaissement_paydunya_pret_token_paydunya'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiqueoperation',
            name='pret',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='prets.pret'),
        ),
    ]
