# Generated by Django 6.1.1 on 2026-09-21 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('date_demande', models.DateField(auto_now_add=True)),
                ('date_echeance', models.DateField()),
                ('date_remboursement', models.DateField(blank=True, null=True)),
                ('date_approbation', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('en_attente', 'En attente'), ('rembourse', 'Remboursé'), ('refuse', 'Refusé'), ('en_retard', 'En retard')], default='en_attente', max_length=20)),
                ('mode_paiement', models.CharField(blank=True, choices=[('especes', 'Espèces'), ('wave', 'Wave'), ('orange_money', 'Orange Money')], max_length=20, null=True)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prêt',
                'verbose_name_plural': 'Prêts',
                'db_table': 'pret',
                'ordering': ['-date_approbation'],
            },
        ),
    ]
