# Generated by Django 6.1.1 on 2026-09-21 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_utilisateur_is_active_utilisateur_is_staff'),
        ('prets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pret',
            name='duree_mois',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pret',
            name='date_echeance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReglePret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_max', models.DecimalField(decimal_places=0, max_digits=12)),
                ('duree_max_mois', models.PositiveIntegerField()),
                ('nombre_prets_simultanes', models.PositiveIntegerField(default=1)),
                ('cotisation_a_jour_obligatoire', models.BooleanField(default=False)),
                ('gie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regle_pret', to='authentication.gie')),
            ],
            options={
                'verbose_name': 'Règle de prêt',
                'verbose_name_plural': 'Règles de prêt',
                'db_table': 'regle_pret',
            },
        ),
    ]
