# Generated by Django 6.1.1 on 2026-09-21 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prets', '0002_pret_duree_mois_alter_pret_date_echeance_reglepret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglepret',
            name='cotisation_a_jour_obligatoire',
            field=models.BooleanField(default=True),
        ),
    ]
