# Generated by Django 6.1.1 on 2026-09-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prets', '0003_alter_reglepret_cotisation_a_jour_obligatoire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pret',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('approuve', 'Approuvé'), ('en_attente', 'En attente'), ('rembourse', 'Remboursé'), ('refuse', 'Refusé'), ('en_retard', 'En retard')], default='en_attente', max_length=20),
        ),
    ]
