# Generated by Django 6.1.1 on 2026-09-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prets', '0004_alter_pret_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='pret',
            name='token_decaissement_paydunya',
            field=models.CharField(blank=True, help_text='Token PayDunya du décaissement (Pay-out) en attente', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pret',
            name='token_paydunya',
            field=models.CharField(blank=True, help_text='Token PayDunya de la facture de remboursement en attente', max_length=255, null=True, unique=True),
        ),
    ]
