# Generated by Django 6.1.1 on 2026-09-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gie',
            name='token_inscription',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='gie',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactf'), ('en_attente', 'En attente')], default='en_attente', max_length=20),
        ),
    ]
