# Generated by Django 6.1.1 on 2026-09-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_gie_token_inscription_alter_gie_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='gie',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
