# Generated by Django 6.1.1 on 2026-09-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_utilisateur_is_active_utilisateur_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gie',
            name='secteur',
        ),
        migrations.AddField(
            model_name='gie',
            name='type_gie',
            field=models.CharField(choices=[('association', 'Association'), ('organisation_communautaire', 'Organisation communautaire'), ('groupement', 'Groupement'), ('autre', 'Autre')], default='association', max_length=50),
            preserve_default=False,
        ),
    ]
