# Generated by Django 6.1.1 on 2026-09-17 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionCotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('cloturee', 'Clôturée')], default='ouverte', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session de cotisation',
                'verbose_name_plural': 'Sessions de cotisation',
                'db_table': 'session_cotisation',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('mode_paiement', models.CharField(blank=True, choices=[('especes', 'Espèces'), ('wave', 'Wave'), ('orange_money', 'Orange Money')], max_length=20, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('paye', 'Payé'), ('en_retard', 'En retard')], default='en_cours', max_length=20)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotisations', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='cotisations.sessioncotisation')),
            ],
            options={
                'verbose_name': 'Cotisation',
                'verbose_name_plural': 'Cotisations',
                'db_table': 'cotisation',
                'unique_together': {('session', 'membre')},
            },
        ),
    ]
