# Generated by Django 6.1.1 on 2026-09-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotisation',
            name='token_paydunya',
            field=models.CharField(blank=True, help_text='Token PayDunya de la facture en attente de confirmation', max_length=255, null=True, unique=True),
        ),
    ]
