# Generated by Django 6.1.1 on 2026-09-23 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0004_utilisateur_is_active_utilisateur_is_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_activite', models.DateTimeField()),
                ('lieu', models.CharField(max_length=255)),
                ('type_activite', models.CharField(choices=[('reunion', 'Réunion'), ('formation', 'Formation'), ('production', 'Production'), ('commerciale', 'Commerciale'), ('autre', 'Autre')], max_length=30)),
                ('ordre_du_jour', models.TextField(blank=True, null=True)),
                ('compte_rendu', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20)),
                ('gie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='authentication.gie')),
                ('organisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activites_organisees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'db_table': 'activite',
                'ordering': ['-date_activite'],
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent')], max_length=20)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='activites.activite')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'db_table': 'presence',
                'constraints': [models.UniqueConstraint(fields=('activite', 'utilisateur'), name='presence_unique_par_activite')],
            },
        ),
    ]
