# Generated by Django 6.1.1 on 2026-09-24 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationutilisateur',
            name='date_lecture',
        ),
    ]
